package common.constants;

/**
 * Created by longnguyen on 1/4/17.
 */
public class ConstantValues {
    public static final String REST_MESSAGE_FIELD_RESEARCHER_ALREADY_REGISTERED = "This Field Researcher already registered with a Journey";

    public static final String REST_MESSAGE_FIELD_RESEARCHER_NOT_REGISTERED = "This Field Researcher has not registered with any Journey";

    public static final String REST_MESSAGE_RESPONSE_UPDATE_SUCCESSFUL = "A new research work has been created";

    public static final String ALERT_MESSAGE_NO_USERNAME_ENTERED = "Please enter your name";

    public static final String ALERT_MESSAGE_QUIT_CONFIRMATION = "Are you sure you want to quit?";

    public static final String BUNDLE_KEY_JOURNEY_FIELD_RESEARCHER_DTO = "BUNDLE_KEY_JOURNEY_FIELD_RESEARCHER_DTO";

    public static final String BUNDLE_KEY_TOUCH_POINT_FIELD_RESEARCHER_DTO = "BUNDLE_KEY_TOUCH_POINT_FIELD_RESEARCHER_DTO";

    public static final String ACTION_LISTENER_VIEW_KEY = "ACTION_LISTENER_VIEW_KEY";

    public static final String ACTION_LISTENER_JOURNEY_SELECTED_POSITION_KEY = "ACTION_LISTENER_JOURNEY_SELECTED_POSITION_KEY";

    public static final String ACTION_LISTENER_MOTION_EVENT_KEY = "ACTION_LISTENER_MOTION_EVENT_KEY";

    public static final String COMPONENT_MAIN_VIEW_BUTTON_RESEARCH_LIST = "COMPONENT_MAIN_VIEW_BUTTON_RESEARCH_LIST";

    public static final String COMPONENT_MAIN_VIEW_TEXT_VIEW_TEXT = "COMPONENT_MAIN_VIEW_TEXT_VIEW_TEXT";

    public static final String COMPONENT_MAIN_VIEW_EDIT_TEXT_USERNAME = "COMPONENT_MAIN_VIEW_EDIT_TEXT_USERNAME";

    public static final String COMPONENT_JOURNEY_LIST_VIEW_BUTTON_SIGN_UP = "COMPONENT_JOURNEY_LIST_VIEW_BUTTON_SIGN_UP";

    public static final String COMPONENT_JOURNEY_LIST_VIEW_RECYCLE_VIEW = "COMPONENT_JOURNEY_LIST_VIEW_RECYCLE_VIEW";

    public static final String COMPONENT_JOURNEY_LIST_VIEW_BUTTON_LABEL_SIGN_UP = "Sign Up";

    public static final String COMPONENT_JOURNEY_LIST_VIEW_BUTTON_LABEL_VIEW = "View";

    public static final String COMPONENT_TOUCH_POINT_LIST_VIEW_LIST_VIEW_TOUCH_POINT_LIST = "COMPONENT_TOUCH_POINT_LIST_VIEW_LIST_VIEW_TOUCH_POINT_LIST";

    public static final String COMPONENT_TOUCH_POINT_LIST_VIEW_TEXT_VIEW_JOURNEY_NAME = "COMPONENT_TOUCH_POINT_LIST_VIEW_TEXT_VIEW_JOURNEY_NAME";

    public static final String COMPONENT_TOUCH_POINT_LIST_VIEW_BUTTON_SUBMIT_JOURNEY = "COMPONENT_TOUCH_POINT_LIST_VIEW_BUTTON_SUBMIT_JOURNEY";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_REACTION = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_REACTION";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_COMMENT = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_COMMENT";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_ACTUAL_DURATION = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_ACTUAL_DURATION";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_TEXT_VIEW_IMAGE = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_TEXT_VIEW_IMAGE";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_IMAGE_PATH = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_EDIT_TEXT_IMAGE_PATH";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_RATING_BAR = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_RATING_BAR";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_BUTTON_SUBMIT = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_BUTTON_SUBMIT";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_IMAGE_BUTTON = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_IMAGE_BUTTON";

    public static final String COMPONENT_TOUCH_POINT_DETAILS_VIEW_SPINNER_ACTUAL_DURATION_UNIT = "COMPONENT_TOUCH_POINT_DETAILS_VIEW_SPINNER_ACTUAL_DURATION_UNIT";

    public static final String OTHERS_STATUS_DONE = "DONE";

    public static final String OTHERS_TIME_UNIT_DAY = "Day";

    public static final String OTHERS_TIME_UNIT_HOUR = "Hour";

    public static final String OTHERS_TIME_UNIT_MINUTE = "Minute";
}
